### ISSUE TITLE
[Android] sometimes  Hub.UnregisterAll method throws exception

### ISSUE THREAD

**Issue by AndreiMisiukevich** [KSemenenko/AzurePushNotificationsForXamarinForms#9]
WindowsAzure.Messaging.NotificationHubResourceNotFoundException

one of two "OnRegister" call cause exception...

  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <183b200ee49746d48fc781625979428e>:0 
  at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <50812bf827614c0faffacac58772b4fa>:0 
  at Android.Runtime.JNIEnv.CallVoidMethod (System.IntPtr jobject, System.IntPtr jmethod, Android.Runtime.JValue* parms) [0x0000e] in <71828dd8fb5f4508815e23d6996c45c2>:0 
  at WindowsAzure.Messaging.NotificationHub.UnregisterAll (System.String pnsHandle) [0x00067] in <15e1a3139a484a5a85c0680e5d11bb86>:0 
  at PeopleWare.Mobile.Droid.PushesService.OnRegistered (Android.Content.Context context, System.String registrationId) [0x00017] in /Users/andreimisiukevich/Desktop/PWnews/Samp/Peopleware.Mobile.UI/Peopleware.Mobile.Droid/MainActivity.cs:122 
  --- End of managed WindowsAzure.Messaging.NotificationHubResourceNotFoundException stack trace ---
com.microsoft.windowsazure.messaging.NotificationHubResourceNotFoundException: Resource not found
	at com.microsoft.windowsazure.messaging.Connection.executeRequest(Connection.java:244)
	at com.microsoft.windowsazure.messaging.Connection.executeRequest(Connection.java:178)
	at com.microsoft.windowsazure.messaging.Connection.executeRequest(Connection.java:134)
	at com.microsoft.windowsazure.messaging.NotificationHub.deleteRegistrationInternal(NotificationHub.java:481)
	at com.microsoft.windowsazure.messaging.NotificationHub.unregisterAll(NotificationHub.java:268)
	at md5ba1d5fec351b953448a62e50ea4bce82.GcmServiceBase.n_onHandleIntent(Native Method)
	at md5ba1d5fec351b953448a62e50ea4bce82.GcmServiceBase.onHandleIntent(GcmServiceBase.java:44)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:211)

**Comment by KSemenenko** [comment]
Hi, please try this https://mobile.azure.com

**Comment by AndreiMisiukevich** [comment]
Hm, honestly speaking, I've not understood

So, I wrote try-catch block with 5-retries count. I think, it can help
